version: "3"

services:
  frontend:
    build: ./tutorial-frontend
    volumes:
      - ./tutorial-frontend:/app
    ports:
      - "80:80"
    environment:
      VUE_APP_ENPOINT_API_BACKEND: "http://127.0.0.1:8089/api"
    networks:
      - front-tier
  
  backend:
    build: ./tutorial-backend
    depends_on:
      - "db"
    volumes:
      - ./tutorial-backend:/app
    ports:
      - "8089:8089"
    environment:
      MONGODB_CONNECTION_STRING: "mongodb://root:password@db:27017"
    networks:
      - back-tier
      - front-tier

  db:
    image: mongo:latest
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    volumes:
      - "db-data:/data/db"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier: